#ifndef CODARIS_VERSION_H
#define CODARIS_VERSION_H

#define CODARIS_VERSION_MAJOR 1
#define CODARIS_VERSION_MINOR 0
#define CODARIS_VERSION_PATCH 0
#define CODARIS_VERSION_STRING "1.0.0-beta.1"

#endif
